name: Create Hotfix and OTA Branches

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., 1.2.3)'
        required: true
        type: string
      bug:
        description: 'Bug identifier (e.g., bug123)'
        required: true
        type: string

jobs:
  create-branches-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch tags from remote
        run: |
          # Fetch all tags from the remote repository to ensure we have the correct ones
          git fetch --tags

      - name: Get commit associated with the tag
        id: tag-commit
        run: |
          # Fetch the commit hash for the tag
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.event.inputs.tag }})
          echo "Tag commit: $TAG_COMMIT"
          echo "::set-output name=commit::$TAG_COMMIT"

      - name: Create a hotfix branch
        id: hotfix-branch
        run: |
          TAG_COMMIT=${{ steps.tag-commit.outputs.commit }}
          BUG=${{ github.event.inputs.bug }}
          HOTFIX_BRANCH="hotfix/${{ github.event.inputs.tag }}/${BUG}"
          
          echo "Creating hotfix branch: $HOTFIX_BRANCH from commit $TAG_COMMIT"
          
          # Checkout the commit and create the hotfix branch
          git checkout $TAG_COMMIT
          git checkout -b $HOTFIX_BRANCH
          
          # Push the hotfix branch to GitHub
          git push origin $HOTFIX_BRANCH

      - name: Create an OTA branch from the hotfix branch
        id: ota-branch
        run: |
          HOTFIX_BRANCH="hotfix/${{ github.event.inputs.tag }}/${{ github.event.inputs.bug }}"
          OTA_BRANCH="ota/${{ github.event.inputs.tag }}/${{ github.event.inputs.bug }}"
          
          echo "Creating OTA branch: $OTA_BRANCH from hotfix branch $HOTFIX_BRANCH"
          
          # Checkout the hotfix branch and create the OTA branch
          git checkout $HOTFIX_BRANCH
          git checkout -b $OTA_BRANCH
          
          # Push the OTA branch to GitHub
          git push origin $OTA_BRANCH

      - name: Create a draft PR for OTA to Hotfix
        id: draft-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the GH_TOKEN environment variable for GitHub CLI authentication
        run: |
          HOTFIX_BRANCH="hotfix/${{ github.event.inputs.tag }}/${{ github.event.inputs.bug }}"
          OTA_BRANCH="ota/${{ github.event.inputs.tag }}/${{ github.event.inputs.bug }}"
          
          echo "Creating draft PR from $OTA_BRANCH to $HOTFIX_BRANCH"
          
          # Create a draft pull request using GitHub CLI (gh)
          gh pr create --base $HOTFIX_BRANCH --head $OTA_BRANCH --title "Draft PR for $OTA_BRANCH to $HOTFIX_BRANCH" --body "This is a draft PR to merge $OTA_BRANCH into $HOTFIX_BRANCH." --draft

      - name: Output created branches and PR
        run: |
          echo "Created branches: $HOTFIX_BRANCH and $OTA_BRANCH"
          echo "Draft PR created from $OTA_BRANCH to $HOTFIX_BRANCH"